#!/bin/bash

read -r -p 'Commit message' desc  # prompt user for commit message
sudo git add .                           # track all files
sudo git add -u                          # track deletes
sudo git commit -m "$desc"               # commit with message
sudo git push heroku master              # push to origin
